import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}

function Navbar() {
  return(
    <div className = "navbar">
        <Link href="/">
          <p>Home</p>
        </Link>
        <Link href="list">
          <p>List</p>
        </Link>
    </div>
  )
}